params:
  learning_rate:
    - 1e-3
  weight_decay:
    - 1e-2
  seed:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
  long_range:
    - 10
  batch_size:
    - 1
    - 8
  scheduler:
    - False
  model_id:
    #- "S"
    #- "B"
    - "L"
  kernel_size:
    #- 3
    - 5
  synthetic:
    - 1.0
  drop_slice_prob:
    - 0.05
  shift_slice_prob:
    - 0.05
  intensity_aug:
    - true
  noise_scale:
    - 0.5
  affine:
    - 0.5
  n_steps:
    - 1_000_000
  small_size:
    #- 112
    - 128
    #- 144
    #- 160
    #- 176
    #- 192
    #- 208
    - 224
    #- 240
    #- 256
    #- 272
    #- 288
    #- 304
    #- 320
    #- 336
    #- 352
    #- 368
  data_setting:
    #- "base"
    #- "liconn"
    #- "multichannel"
    #- "neg_guidance"
    #- "no_touch_thick"
    #- "pos_guidance"
    #- "slice_perturbed"
    #- "touching_thin"
    - "train_100"
  base_data_path:
    - "/cajal/nvmescratch/projects/NISB/"
  save_path:
    - "/cajal/scratch/projects/misc/zuzur/ss3"
  exp_name:
    - "debug1GPU"
  real_data_path: #https://colab.research.google.com/github/funkelab/lsd/blob/master/lsd/tutorial/notebooks/lsd_data_download.ipynb
    - "/cajal/scratch/projects/misc/mdraw/data/funke/zebrafinch/training/"
  auto_resubmit:
    - False
  distributed:
    - True
  compile:
    - False
  validate_extern:
    - True
  augment:
    - False